/* Spatial Transcriptomics 互動式考題 — 題庫資料（中英雙語）
 * Bilingual question bank for the 15-chapter ST tutorial.
 * type: "single" 單選 | "multi" 多選 | "tf" 是非
 * single ans: "A"|"B"|"C"|"D"
 * multi  ans: ["A","C"]
 * tf     ans: "T"|"F"
 * 中英對照：stem/A/B/C/D/exp 為中文；stem_en/A_en/B_en/C_en/D_en/exp_en 為英文
 */
window.QUIZ_DATA = {
  st: {
    label: "Spatial Transcriptomics 互動考題",
    label_en: "Spatial Transcriptomics Interactive Quiz",
    labels_en: {
      "基礎概念": "Foundations",
      "核心分析流程": "Core Analysis Pipeline",
      "進階分析主題": "Advanced Topics",
      "Step 1：總覽 (Overview)": "Step 1: Overview",
      "Step 2：平台比較 (Platforms)": "Step 2: Platform Comparison",
      "Step 3：品質管控 (QC)": "Step 3: Quality Control (QC)",
      "Step 4：標準化 (Normalization)": "Step 4: Normalization",
      "Step 5：降維與特徵 (DimRed)": "Step 5: Dimensionality Reduction",
      "Step 6：空間區域辨識 (Spatial Domains)": "Step 6: Spatial Domain Identification",
      "Step 7：空間變異基因 (SVGs)": "Step 7: Spatially Variable Genes",
      "Step 8：細胞類型解卷積 (Deconvolution)": "Step 8: Cell Type Deconvolution",
      "Step 9：與 scRNA-seq 整合 (scInteg)": "Step 9: scRNA-seq Integration",
      "Step 10：空間細胞通訊 (CCC)": "Step 10: Spatial Cell-Cell Communication",
      "Step 11：生態棲位 (Niche)": "Step 11: Niche & Microenvironment",
      "Step 12：空間軌跡 (Trajectory)": "Step 12: Spatial Trajectory",
      "Step 13：多樣本整合 (Multi-sample)": "Step 13: Multi-sample Integration",
      "Step 14：細胞切割 (Segmentation)": "Step 14: Cell Segmentation",
      "Step 15：Visium HD 與病理影像": "Step 15: Visium HD & Histology"
    },
    subjects: {

"基礎概念": {

"Step 1：總覽 (Overview)": [
  { type:"single",
    stem:"關於 Spatial Transcriptomics (ST) 與 scRNA-seq 的關係，下列何者最正確？",
    stem_en:"Which best describes the relationship between Spatial Transcriptomics (ST) and scRNA-seq?",
    A:"ST 是 scRNA-seq 的升級版，會完全取代 scRNA-seq", A_en:"ST is an upgrade that will fully replace scRNA-seq",
    B:"兩者互補：scRNA-seq 給細胞類型 reference，ST 把它放回組織座標", B_en:"They are complementary: scRNA-seq gives cell-type references; ST puts them back into tissue coordinates",
    C:"ST 不需要任何 scRNA-seq 資料", C_en:"ST never needs scRNA-seq data",
    D:"ST 和 scRNA-seq 完全相同", D_en:"ST and scRNA-seq are identical",
    ans:"B",
    exp:"實務工作流程：先用 scRNA-seq 建立 cell-type reference，再用 ST 把這些細胞類型映射回組織原本的位置。",
    exp_en:"Standard workflow: build cell-type references with scRNA-seq, then map them back into tissue locations using ST." },
  { type:"single",
    stem:"想要回答「腫瘤侵襲前緣的免疫細胞跟腫瘤細胞如何互動」這個問題，最適合的技術是？",
    stem_en:"To answer 'how do immune cells interact with tumor cells at the invasion front', which technology fits best?",
    A:"Bulk RNA-seq", A_en:"Bulk RNA-seq",
    B:"解離後的 scRNA-seq", B_en:"Dissociated scRNA-seq",
    C:"Spatial Transcriptomics", C_en:"Spatial Transcriptomics",
    D:"qPCR", D_en:"qPCR",
    ans:"C",
    exp:"ST 同時保留表達與位置，最適合研究「物理鄰接」的細胞互動。scRNA-seq 在解離過程中失去了空間關係。",
    exp_en:"ST preserves both expression and location, ideal for studying spatially adjacent interactions. scRNA-seq loses spatial info during dissociation." },
  { type:"single",
    stem:"關於 spot-based 與 image-based ST 的核心差別，下列何者正確？",
    stem_en:"Key difference between spot-based and image-based ST?",
    A:"Spot-based 通常涵蓋全轉錄組但解析度較低；Image-based 是單細胞解析度但侷限於 panel", A_en:"Spot-based: whole-transcriptome but lower resolution; Image-based: single-cell resolution but panel-limited",
    B:"兩者都是單細胞解析度，差別只在通量", B_en:"Both are single-cell; only throughput differs",
    C:"Image-based 可以量到任意基因", C_en:"Image-based can measure any gene",
    D:"Spot-based 不需要 deconvolution", D_en:"Spot-based does not need deconvolution",
    ans:"A",
    exp:"這是兩家技術的核心 trade-off：spot-based (Visium 等) 全轉錄組但每 spot 多細胞混合；image-based (Xenium/MERFISH 等) 單細胞但只測 panel 內基因。",
    exp_en:"This is the core trade-off: spot-based (Visium etc.) is whole-transcriptome but mixes cells per spot; image-based (Xenium/MERFISH) is single-cell but limited to panel genes." },
  { type:"single",
    stem:"在 ST 流程中，下列哪一個步驟是相對於 scRNA-seq「新增」出來、特別重要的？",
    stem_en:"Which step is genuinely new and especially important in ST compared to scRNA-seq?",
    A:"PCA", A_en:"PCA",
    B:"空間區域辨識 (Spatial Domain) 與 SVG", B_en:"Spatial Domain identification + Spatially Variable Genes",
    C:"UMAP", C_en:"UMAP",
    D:"過濾低品質細胞", D_en:"Filtering low-quality cells",
    ans:"B",
    exp:"PCA、UMAP、QC 都是 scRNA 也有的步驟。Spatial Domain 與 SVG 是 ST 特有的、利用空間座標的新分析。",
    exp_en:"PCA, UMAP, and QC also exist in scRNA. Spatial Domain ID and SVGs are uniquely enabled by spatial coordinates." },
  { type:"tf",
    stem:"是非題：所有 ST 平台都需要做細胞解卷積 (deconvolution)。",
    stem_en:"True/False: All ST platforms require cell-type deconvolution.",
    ans:"F",
    exp:"只有 spot-based 平台 (Visium/Slide-seq/Stereo-seq) 因為一個 spot 含多細胞才需要 deconvolution。Image-based 平台 (Xenium/MERFISH) 已是單細胞解析度，做 segmentation + clustering 即可。",
    exp_en:"Only spot-based platforms (Visium/Slide-seq/Stereo-seq) need deconvolution because each spot contains multiple cells. Image-based platforms (Xenium/MERFISH) are already single-cell, requiring only segmentation + clustering." },
  { type:"multi",
    stem:"下列哪些是 ST 的典型應用情境？（多選）",
    stem_en:"Which are typical ST applications? (Multiple)",
    A:"觀察基因表達跟解剖學結構（如皮層、髓質）的對應", A_en:"Map gene expression onto anatomy (cortex, medulla, etc.)",
    B:"研究腫瘤侵襲前緣的細胞互動", B_en:"Study cellular interactions at tumor invasion fronts",
    C:"H&E 影像 + 表達雙模態整合", C_en:"H&E image + expression dual-modality integration",
    D:"研究發育時細胞如何沿軸排列", D_en:"Study how cells arrange along developmental axes",
    ans:["A","B","C","D"],
    exp:"以上全部都是 ST 的核心優勢，因為 ST 能同時保留表達 + 空間 + 形態三種資訊。",
    exp_en:"All four are core ST strengths because ST simultaneously preserves expression + space + morphology." },
  { type:"single",
    stem:"關於 Visium 55 µm spot 的細胞涵蓋，下列何者最接近實際？",
    stem_en:"What's the typical cell coverage of a Visium 55 µm spot?",
    A:"恰好 1 個細胞", A_en:"Exactly 1 cell",
    B:"約 1–10 個細胞", B_en:"Roughly 1–10 cells",
    C:"上百個細胞", C_en:"Hundreds of cells",
    D:"從不包含細胞", D_en:"Never contains cells",
    ans:"B",
    exp:"Visium 55 µm spot 大約涵蓋 1–10 個細胞（依組織密度而定），這就是為什麼需要 deconvolution 才能拆出 cell-type 比例。",
    exp_en:"A Visium 55 µm spot typically covers 1–10 cells depending on tissue density — exactly why deconvolution is needed to estimate cell-type proportions." },
  { type:"tf",
    stem:"是非題：在 ST 流程中，scRNA-seq 與 ST 是「替代」關係——選了一個就不需要另一個。",
    stem_en:"True/False: scRNA-seq and ST are 'either-or' — once you choose one, you don't need the other.",
    ans:"F",
    exp:"兩者是互補：scRNA-seq 給高解析度的細胞類型 reference；ST 把這些 reference 放回組織。實際 paper 經常兩種都做。",
    exp_en:"They are complementary: scRNA-seq provides a high-resolution cell-type reference; ST puts it back into tissue. Real studies routinely combine both." }
],

"Step 2：平台比較 (Platforms)": [
  { type:"single",
    stem:"想做整個小鼠胚胎切片、看不同器官如何分化，最合適的平台？",
    stem_en:"To profile a whole mouse embryo section to study organ differentiation, the best platform is?",
    A:"Visium 6.5×6.5 mm", A_en:"Visium 6.5×6.5 mm",
    B:"Xenium 12×24 mm", B_en:"Xenium 12×24 mm",
    C:"Stereo-seq（13×13 cm）", C_en:"Stereo-seq (13×13 cm)",
    D:"STARmap 1 mm²", D_en:"STARmap 1 mm²",
    ans:"C",
    exp:"Stereo-seq 的 chip 面積最大（最高 13×13 cm），且解析度可達 500 nm，是整器官 / 整胚胎研究的首選。",
    exp_en:"Stereo-seq has the largest chip area (up to 13×13 cm) plus 500 nm resolution — ideal for whole-organ or whole-embryo studies." },
  { type:"single",
    stem:"已經知道要看的 60 個免疫標記基因，且樣本是 FFPE，最合適？",
    stem_en:"You have a 60-gene immune panel and FFPE tissue. Best fit?",
    A:"Visium FFPE", A_en:"Visium FFPE",
    B:"Xenium 自訂 panel", B_en:"Xenium custom panel",
    C:"Slide-seq V2", C_en:"Slide-seq V2",
    D:"Stereo-seq", D_en:"Stereo-seq",
    ans:"B",
    exp:"已知目標基因 + FFPE → image-based 自訂 panel 最有效率，能拿到單細胞解析、且 panel 為自訂的精準訊號。",
    exp_en:"Defined targets + FFPE → image-based custom panel is most efficient: single-cell resolution and precise panel signal." },
  { type:"single",
    stem:"關於 FFPE 樣本的品質指標，下列敘述何者正確？",
    stem_en:"Which is correct about FFPE QC metrics?",
    A:"應檢查 DV200，建議 ≥ 30%", A_en:"Check DV200, target ≥ 30%",
    B:"RIN 是 FFPE 唯一指標", B_en:"RIN is the only FFPE metric",
    C:"FFPE 不適合做 ST", C_en:"FFPE is not compatible with ST",
    D:"FFPE 切片可以厚到 100 µm 也沒問題", D_en:"FFPE sections can routinely be 100 µm thick",
    ans:"A",
    exp:"FFPE 因為 RNA 已斷裂，看 DV200（>200 nt 片段比例），Visium FFPE 建議 ≥ 30%。RIN 主要用於新鮮冷凍。",
    exp_en:"FFPE RNA is fragmented, so use DV200 (% fragments > 200 nt) — Visium FFPE wants ≥ 30%. RIN is mainly for fresh frozen." },
  { type:"single",
    stem:"Visium HD 的原始 bin 大小為何？",
    stem_en:"What is Visium HD's native bin size?",
    A:"55 µm", A_en:"55 µm",
    B:"10 µm", B_en:"10 µm",
    C:"2 µm × 2 µm 連續鋪滿", C_en:"2 µm × 2 µm tiled continuously",
    D:"500 nm", D_en:"500 nm",
    ans:"C",
    exp:"Visium HD 的 oligonucleotide squares 是 2 µm 連續鋪滿，雖然 10x 推薦下游分析用 8 µm bin（已聚合）。",
    exp_en:"Visium HD's oligonucleotide squares are continuous 2 µm tiles, although 10x recommends 8 µm aggregated bins for downstream analysis." },
  { type:"multi",
    stem:"下列哪些屬於 image-based / FISH-based ST 平台？（多選）",
    stem_en:"Which are image-based / FISH-based ST platforms? (Multiple)",
    A:"10x Visium", A_en:"10x Visium",
    B:"10x Xenium", B_en:"10x Xenium",
    C:"Vizgen MERFISH", C_en:"Vizgen MERFISH",
    D:"NanoString CosMx SMI", D_en:"NanoString CosMx SMI",
    ans:["B","C","D"],
    exp:"Visium 是 spot-based / NGS-based。Xenium、MERFISH、CosMx 都是 image-based 用 FISH 或 in-situ sequencing 反覆顯微成像。",
    exp_en:"Visium is spot-based / NGS-based. Xenium, MERFISH, and CosMx are all image-based, using FISH or in situ sequencing." },
  { type:"single",
    stem:"關於 Xenium 與 MERSCOPE 的比較，下列何者較正確？",
    stem_en:"Comparing Xenium and MERSCOPE, which statement is more accurate?",
    A:"兩者效能完全相同", A_en:"Their performance is identical",
    B:"Xenium 對 FFPE 處理較佳；MERSCOPE 在高品質 RNA 上敏感度略勝", B_en:"Xenium handles FFPE better; MERSCOPE has slightly higher sensitivity on high-quality RNA",
    C:"MERSCOPE 不能用於組織切片", C_en:"MERSCOPE cannot work on tissue sections",
    D:"Xenium 不支援 FFPE", D_en:"Xenium does not support FFPE",
    ans:"B",
    exp:"Xenium 對降解 RNA（FFPE）容忍度高；MERSCOPE 在 RIN 高的新鮮樣本上敏感度通常略勝。兩者在腦圖譜（Allen）等場景都常見。",
    exp_en:"Xenium tolerates degraded RNA (FFPE) well; MERSCOPE has slightly higher sensitivity on high-RIN fresh samples. Both are common in brain atlases (e.g., Allen)." },
  { type:"tf",
    stem:"是非題：image-based 平台（如 Xenium）可以量到 panel 之外的任何基因。",
    stem_en:"True/False: image-based platforms (e.g., Xenium) can detect any gene outside the panel.",
    ans:"F",
    exp:"image-based 平台只能量 panel 內基因（panel 大小約 100–6000）。要看 panel 外基因得改用 spot-based（Visium 等）。",
    exp_en:"Image-based platforms only detect panel genes (panel size ~100–6000). To see off-panel genes, switch to spot-based (Visium etc.)." },
  { type:"single",
    stem:"關於 Visium FFPE 的定序深度建議，下列何者較接近實務？",
    stem_en:"Regarding Visium FFPE sequencing depth, which is closer to practice?",
    A:"標準 25 k reads/spot 通常已經足夠", A_en:"The standard 25 k reads/spot is usually enough",
    B:"100–120 k reads/spot 才能看到 transcript diversity", B_en:"Need 100–120 k reads/spot to capture transcript diversity",
    C:"1 k reads/spot 即可", C_en:"1 k reads/spot is sufficient",
    D:"10 M reads/spot 才有意義", D_en:"Only 10 M reads/spot is meaningful",
    ans:"B",
    exp:"FFPE 因為 RNA 品質較低，標準 25 k reads/spot 經常不足，2025 實務指南建議拉到 100–120 k 才能看到足夠 transcript diversity。",
    exp_en:"FFPE has lower RNA quality, so 25 k reads/spot is often insufficient. The 2025 practical guide recommends 100–120 k reads/spot for adequate transcript diversity." },
  { type:"single",
    stem:"哪一個平台具有「全轉錄組 + image-based」的特色，但代價是每基因敏感度有取捨？",
    stem_en:"Which platform offers 'whole-transcriptome + image-based' at the cost of per-gene sensitivity trade-offs?",
    A:"Visium", A_en:"Visium",
    B:"Slide-seq V2", B_en:"Slide-seq V2",
    C:"NanoString CosMx SMI（Whole Transcriptome）", C_en:"NanoString CosMx SMI (Whole Transcriptome)",
    D:"Stereo-seq", D_en:"Stereo-seq",
    ans:"C",
    exp:"CosMx SMI 提供 Whole Transcriptome (~18 000) 的 image-based 選項，是少見的「兩者兼具」方案，但每基因敏感度與細胞通量相對其他 panel 平台需取捨。",
    exp_en:"CosMx SMI offers a Whole Transcriptome (~18 000) image-based option — a rare 'best of both' solution, with trade-offs in per-gene sensitivity and throughput vs panel platforms." }
]

},

"核心分析流程": {

"Step 3：品質管控 (QC)": [
  { type:"single",
    stem:"在 Visium 心臟切片整片 MT% 都偏高，最佳處置？",
    stem_en:"Visium cardiac section shows globally elevated MT%. Best response?",
    A:"用 5% 嚴格過濾", A_en:"Apply strict 5% cutoff",
    B:"完全不做 MT% 檢查", B_en:"Skip MT% entirely",
    C:"把閾值依組織特性調高，且看空間分佈是否跟解剖結構一致", C_en:"Raise threshold to fit tissue biology and verify spatial distribution against anatomy",
    D:"移除所有 MT 基因", D_en:"Remove all MT genes",
    ans:"C",
    exp:"心肌組織 MT% 天然偏高，閾值應依組織背景調整；同時用 spatial 圖確認分佈是否符合解剖。",
    exp_en:"Cardiomyocytes naturally have high MT% — threshold must follow tissue biology. Use spatial maps to confirm distributions match anatomy." },
  { type:"single",
    stem:"SpotSweeper 的核心優勢是？",
    stem_en:"What is the key advantage of SpotSweeper?",
    A:"自動估算 batch effect", A_en:"Estimates batch effects",
    B:"比較每個 spot 與其空間鄰域，找出局部離群", B_en:"Compares each spot with its spatial neighborhood to flag local outliers",
    C:"做 doublet detection", C_en:"Performs doublet detection",
    D:"跟 Cellpose 一樣是切割工具", D_en:"Is a segmentation tool like Cellpose",
    ans:"B",
    exp:"SpotSweeper 把每個 spot 跟 k 鄰居（Visium 用 k=36）比較，標記出空間鄰域格格不入的 spot，比 global threshold 更精準。",
    exp_en:"SpotSweeper compares each spot with k spatial neighbors (k=36 for Visium hex grid) to flag local outliers — more accurate than global thresholds." },
  { type:"single",
    stem:"為什麼「nFeature 高」在 Visium 不一定代表 doublet？",
    stem_en:"Why doesn't 'high nFeature' always mean doublet in Visium?",
    A:"因為一個 spot 本來就可能涵蓋 1–10 個細胞", A_en:"Because each spot can naturally contain 1–10 cells",
    B:"因為 Visium 不會發生 doublet", B_en:"Because Visium never produces doublets",
    C:"因為 nFeature 是錯誤的指標", C_en:"Because nFeature is a wrong metric",
    D:"因為 Visium 有 in_tissue 標籤", D_en:"Because Visium has the in_tissue flag",
    ans:"A",
    exp:"Visium 一個 spot 本來就可能涵蓋多顆細胞，nFeature 高很可能只是反映該區細胞密集，並非 doublet。",
    exp_en:"A Visium spot natively contains multiple cells, so high nFeature may simply reflect denser tissue, not a doublet." },
  { type:"multi",
    stem:"下列哪些屬於 ST 特有（相對於 scRNA-seq）的 QC 重點？（多選）",
    stem_en:"Which are ST-specific QC concerns (vs scRNA-seq)? (Multiple)",
    A:"in_tissue 標籤檢查", A_en:"in_tissue flag inspection",
    B:"組織覆蓋與 H&E 影像目視", B_en:"Tissue coverage + visual H&E inspection",
    C:"SpotSweeper 局部離群", C_en:"SpotSweeper local outliers",
    D:"基因 PCR 引物設計", D_en:"Gene PCR primer design",
    ans:["A","B","C"],
    exp:"in_tissue、影像目視、空間離群都是 ST 才有的 QC 步驟。PCR primer 跟 ST 流程無關。",
    exp_en:"in_tissue, image inspection, and spatial outliers are ST-specific QC steps. PCR primer design is unrelated." },
  { type:"tf",
    stem:"是非題：scRNA 的 QC 指標可以「直接」搬到 ST 不必修改。",
    stem_en:"True/False: scRNA QC metrics can be applied 'directly' to ST without modification.",
    ans:"F",
    exp:"ST 一個 spot 可能含 0–10 個細胞，「一 barcode = 一細胞」假設不成立。需要重新詮釋 nFeature/nCount 並加入 in_tissue 與空間離群檢查。",
    exp_en:"In ST a spot can contain 0–10 cells, breaking the 'one barcode = one cell' assumption. nFeature/nCount must be reinterpreted, plus add in_tissue and spatial outlier checks." },
  { type:"single",
    stem:"Visium FFPE 因為使用 probe-based 化學，下列何者通常會比新鮮冷凍偏低？",
    stem_en:"Because Visium FFPE uses probe-based chemistry, which is usually lower than fresh-frozen?",
    A:"percent.mt", A_en:"percent.mt",
    B:"基因總數 (panel 大小)", B_en:"Total gene panel size",
    C:"in_tissue 比例", C_en:"in_tissue fraction",
    D:"細胞密度", D_en:"Cell density",
    ans:"A",
    exp:"FFPE probe-based 不大量偵測 MT 轉錄本，所以 MT% 通常較新鮮冷凍偏低；過度套用 5% 閾值反而可能砍掉好細胞。",
    exp_en:"FFPE probe-based chemistry doesn't capture MT transcripts as heavily, so MT% is usually lower than fresh-frozen. Applying a strict 5% cutoff may discard good cells." },
  { type:"multi",
    stem:"下列哪些做法符合 ST QC 的最佳實踐？（多選）",
    stem_en:"Which practices fit ST QC best practices? (Multiple)",
    A:"先看 spatial featureplot 觀察分佈再下閾值", A_en:"Plot spatial feature maps before setting thresholds",
    B:"多樣本用 per-sample MAD adaptive threshold", B_en:"Use per-sample MAD adaptive thresholds across samples",
    C:"完全不檢查 H&E 影像，靠數值即可", C_en:"Skip H&E inspection entirely, rely on numbers",
    D:"用 SpotSweeper 偵測 fold/bubble 損傷", D_en:"Use SpotSweeper to flag fold/bubble damage",
    ans:["A","B","D"],
    exp:"A、B、D 是當前最佳實踐；H&E 影像必須要看，染色不均、皺褶、氣泡都會造成偏差。",
    exp_en:"A, B, D are current best practices. H&E inspection is mandatory — uneven staining, folds, and bubbles all introduce bias." },
  { type:"single",
    stem:"關於 in_tissue 標籤，下列何者較正確？",
    stem_en:"About the in_tissue flag, which is correct?",
    A:"它由 Space Ranger 自動偵測，務必檢查 H&E 影像確認沒有誤判", A_en:"It is auto-detected by Space Ranger; always check H&E to confirm no misclassification",
    B:"它與 H&E 完全無關", B_en:"It is unrelated to H&E",
    C:"它代表 doublet 機率", C_en:"It represents doublet probability",
    D:"它代表 cell 數", D_en:"It represents cell count",
    ans:"A",
    exp:"in_tissue 是 Space Ranger 根據 H&E 影像自動標記「該 spot 是否落在組織內」，但染色淡或邊緣模糊時會誤判，需人工確認。",
    exp_en:"in_tissue is Space Ranger's auto label for whether a spot lies within tissue, based on H&E. Pale staining or fuzzy edges can cause misclassification — manual review is needed." },
  { type:"tf",
    stem:"是非題：對於富血管組織，HBA/HBB 比例偏高通常代表「該 spot 壞了」。",
    stem_en:"True/False: For vascular-rich tissue, elevated HBA/HBB usually means 'the spot is bad'.",
    ans:"F",
    exp:"血管豐富區的高 HB% 多半反映「該區域富含紅血球」這個生物事實，而非 spot 品質差；應視組織背景判斷而非一刀切。",
    exp_en:"High HB% in vascular regions usually reflects the biological fact that the area is rich in red blood cells, not poor spot quality — interpret in tissue context, not by global cutoffs." }
],

"Step 4：標準化 (Normalization)": [
  { type:"single",
    stem:"為什麼在 spot-based ST 上「強制每 spot 標準化到相同總量」可能造成資訊流失？",
    stem_en:"Why can 'force-scale every spot to the same total' lose information in spot-based ST?",
    A:"因為 NGS 不準", A_en:"Because NGS is inaccurate",
    B:"因為 log 轉換是有損的", B_en:"Because log transform is lossy",
    C:"因為 spot 的總 UMI 部分反映了真實細胞密度", C_en:"Because total UMI per spot partly reflects true cell density",
    D:"因為 Visium 不允許標準化", D_en:"Because Visium doesn't allow normalization",
    ans:"C",
    exp:"在 ST 上 library size 差異不只是技術噪音——細胞密集區真的會有更多 RNA。一刀切標準化會洗掉這個生物訊號。",
    exp_en:"In ST, library-size differences aren't pure technical noise — dense regions truly have more RNA. Force-scaling wipes out this biological signal." },
  { type:"single",
    stem:"對於混合細胞嚴重的 Visium spot，下列敘述何者較合理？",
    stem_en:"For Visium spots with strong cell-type mixing, which is more reasonable?",
    A:"SCTransform 仍然完全有效", A_en:"SCTransform remains fully appropriate",
    B:"NB 假設可能失真，LogNormalize 通常是穩定起點", B_en:"NB assumption may break — LogNormalize is a robust default",
    C:"不需要任何 normalization", C_en:"No normalization needed",
    D:"只能用 raw counts", D_en:"Only raw counts can be used",
    ans:"B",
    exp:"SCTransform 假設 expression 服從 NB 分佈；混合細胞 spot 的 mean–variance 不一定符合，LogNormalize 簡單穩定。",
    exp_en:"SCTransform assumes NB-distributed expression; mixed-cell spots may not follow it. LogNormalize is simple and robust." },
  { type:"single",
    stem:"scran 的 size factor 為什麼比簡單的 library size 穩定？",
    stem_en:"Why are scran size factors more stable than simple library sizes?",
    A:"它先粗分群再 deconvolution，避免高表達基因主宰", A_en:"It pre-clusters and uses deconvolution to avoid bias from top genes",
    B:"它直接抹掉 library size", B_en:"It just zeroes out library size",
    C:"它只能用在 image-based 平台", C_en:"It only works on image-based platforms",
    D:"它跟 scRNA 沒有關係", D_en:"It is unrelated to scRNA",
    ans:"A",
    exp:"scran 的 quickCluster + computeSumFactors 流程在每個粗群內 pooling，能避免少數高表達基因主宰 size factor。",
    exp_en:"scran's quickCluster + computeSumFactors pools within rough clusters, preventing a few high-expression genes from dominating the size factor." },
  { type:"multi",
    stem:"下列哪些是 ST 標準化常用的方法？（多選）",
    stem_en:"Which are common ST normalization methods? (Multiple)",
    A:"LogNormalize", A_en:"LogNormalize",
    B:"SCTransform", B_en:"SCTransform",
    C:"scran size factor", C_en:"scran size factor",
    D:"BLAST", D_en:"BLAST",
    ans:["A","B","C"],
    exp:"前三者都是 ST 標準化常用方法。BLAST 是序列比對工具，跟標準化無關。",
    exp_en:"The first three are common ST normalization methods. BLAST is a sequence-alignment tool, unrelated." },
  { type:"tf",
    stem:"是非題：對於 image-based 平台（如 Xenium, MERFISH）的單細胞解析資料，SCTransform 的 NB 假設較容易回到合理範圍。",
    stem_en:"True/False: For image-based platforms (e.g. Xenium, MERFISH) with single-cell data, SCTransform's NB assumption is more likely to hold.",
    ans:"T",
    exp:"image-based 平台是真正單細胞解析，跟 scRNA 場景接近，NB 假設較成立，SCTransform 可比照 scRNA 用。",
    exp_en:"Image-based platforms achieve true single-cell resolution, similar to scRNA — the NB assumption is more reasonable, and SCTransform behaves like in scRNA." },
  { type:"single",
    stem:"2024 之後 scverse / Bioconductor 對 spot-based ST 的「預設」normalization 共識較接近？",
    stem_en:"Post-2024 scverse / Bioconductor consensus default for spot-based ST is closest to?",
    A:"預設用 LogNormalize 即可，PCA 雜亂時再考慮 SCTransform", A_en:"Default LogNormalize; switch to SCTransform if PCA looks noisy",
    B:"必須用 SCTransform，否則結果不可靠", B_en:"Must use SCTransform, otherwise unreliable",
    C:"不應該標準化", C_en:"Should not normalize at all",
    D:"用 z-score 即可", D_en:"Just use z-score",
    ans:"A",
    exp:"由於混合細胞 spot 對 SCTransform 假設不友善，目前共識是 LogNormalize 為穩定起點，視 PCA 結構決定是否再升級。",
    exp_en:"Mixed-cell spots violate SCTransform assumptions, so LogNormalize is the recommended default, with SCTransform reserved for noisy PCA cases." },
  { type:"single",
    stem:"做 deconvolution 時，下列何者考量較合適？",
    stem_en:"When doing deconvolution, which consideration is more appropriate?",
    A:"deconvolution 演算法通常需要 raw 或 size-factor 校正後的 counts，而非 log-normalized 矩陣", A_en:"Deconvolution typically wants raw or size-factor-corrected counts, not log-normalized matrices",
    B:"必須先做 PCA 再做 deconvolution", B_en:"Must run PCA before deconvolution",
    C:"deconvolution 不需要任何 expression", C_en:"Deconvolution doesn't need any expression",
    D:"用 z-score 後的矩陣最佳", D_en:"z-scored matrices are best",
    ans:"A",
    exp:"cell2location/RCTD 等多數 deconvolution 工具假設 NB/Poisson，輸入 raw 或 size-factor 校正過的 counts，而不是 log-normalized 數值。",
    exp_en:"cell2location/RCTD and most deconvolution tools assume NB/Poisson and expect raw or size-factor-adjusted counts — not log-normalized values." },
  { type:"tf",
    stem:"是非題：normalization 的選擇應該依照下游分析任務（domain 分群 / deconvolution / SVG）有所不同。",
    stem_en:"True/False: Normalization choice should depend on the downstream task (domain clustering / deconvolution / SVG).",
    ans:"T",
    exp:"如 spatial domain 通常想保留密度差異；deconvolution 要 raw counts；SVG 對 LogNormalize 即可。應視任務調整。",
    exp_en:"E.g., spatial domain analysis often wants density preserved; deconvolution needs raw counts; SVGs work with LogNormalize. Tailor to the task." }
],

"Step 5：降維與特徵 (DimRed)": [
  { type:"single",
    stem:"為什麼純 PCA + Leiden 在 ST 常常產生「空間不連續」的 cluster？",
    stem_en:"Why does plain PCA + Leiden often produce 'spatially-discontinuous' clusters in ST?",
    A:"因為 PCA 不適合 ST", A_en:"PCA isn't suitable for ST",
    B:"因為它把空間資訊完全忽略，只看 expression", B_en:"It ignores space entirely, considering only expression",
    C:"因為 ST 沒有空間資訊", C_en:"Because ST has no spatial info",
    D:"因為 BANKSY 是錯的", D_en:"Because BANKSY is wrong",
    ans:"B",
    exp:"PCA + Leiden 完全不利用空間，只看 expression 相似度，所以 cluster 不一定空間連續。BANKSY 等空間感知方法把鄰域納入嵌入後就改善了。",
    exp_en:"PCA + Leiden ignores space and uses only expression similarity, so clusters need not be spatially contiguous. Spatially-aware methods like BANKSY add neighborhood to the embedding." },
  { type:"single",
    stem:"BANKSY 的 λ 參數調得很大會發生什麼？",
    stem_en:"What happens if BANKSY's λ is set very high?",
    A:"完全跟著鄰居走，cluster 變得平滑、可能模糊邊界差異", A_en:"Embedding follows neighbors heavily; clusters smooth out — boundaries may blur",
    B:"完全等同於 PCA", B_en:"Becomes equivalent to PCA",
    C:"cluster 數一定變多", C_en:"Always increases cluster count",
    D:"不影響任何結果", D_en:"Has no effect",
    ans:"A",
    exp:"BANKSY λ 控制 self vs neighbor 權重；λ 大 → 嵌入幾乎全靠鄰居 → 結果平滑但邊界容易被洗掉。",
    exp_en:"BANKSY's λ controls self vs neighbor weight; large λ → embedding driven by neighbors → smoother but boundary contrast vanishes." },
  { type:"single",
    stem:"SVG 跟 HVG 最關鍵的差別？",
    stem_en:"Key difference between SVG and HVG?",
    A:"SVG 只能用 R", A_en:"SVG only runs in R",
    B:"SVG 考慮空間自相關，HVG 只看整體變異", B_en:"SVG considers spatial autocorrelation; HVG only looks at overall variance",
    C:"SVG 一定比 HVG 多", C_en:"SVGs are always more numerous than HVGs",
    D:"SVG 跟 HVG 是同義詞", D_en:"SVG and HVG are synonyms",
    ans:"B",
    exp:"HVG 只看整體變異（不考慮空間）；SVG 用 Moran's I 等指標檢查表達是否跟空間有結構性關聯。HVG 不一定 spatial。",
    exp_en:"HVG only looks at overall variance (no spatial); SVG uses statistics like Moran's I to test spatial autocorrelation. HVG isn't necessarily spatial." },
  { type:"multi",
    stem:"下列哪些屬於空間感知 (spatially-aware) 的降維 / 嵌入方法？（多選）",
    stem_en:"Which are spatially-aware dimensionality reduction / embedding methods? (Multiple)",
    A:"BANKSY", A_en:"BANKSY",
    B:"PCA", B_en:"PCA",
    C:"SpaceFlow encoder", C_en:"SpaceFlow encoder",
    D:"STAGATE", D_en:"STAGATE",
    ans:["A","C","D"],
    exp:"BANKSY、SpaceFlow、STAGATE 都把空間鄰域納入嵌入。PCA 不考慮空間。",
    exp_en:"BANKSY, SpaceFlow, and STAGATE all incorporate spatial neighborhoods. PCA ignores space." },
  { type:"tf",
    stem:"是非題：在 ST 中，HVG 一定是 SVG。",
    stem_en:"True/False: In ST, an HVG is always an SVG.",
    ans:"F",
    exp:"HVG 變異可能是雜訊或全組織分散；SVG 才要求變異跟空間有關聯。HVG 不一定 spatial。",
    exp_en:"HVG variance can be noise or scattered; SVGs require structured spatial variance. HVGs need not be SVGs." },
  { type:"single",
    stem:"關於 BANKSY 在 Seurat v5 的整合，下列何者正確？",
    stem_en:"Regarding BANKSY's integration in Seurat v5, which is correct?",
    A:"Seurat v5 已內建 RunBanksy()，可搭配 Visium / HD / Xenium", A_en:"Seurat v5 ships RunBanksy() and supports Visium / HD / Xenium",
    B:"BANKSY 只能用 Python", B_en:"BANKSY is Python-only",
    C:"BANKSY 跟 Seurat 不相容", C_en:"BANKSY is incompatible with Seurat",
    D:"BANKSY 取代 PCA，不能再做 PCA", D_en:"BANKSY replaces PCA — PCA can no longer be run",
    ans:"A",
    exp:"Seurat v5 把 BANKSY 寫進核心，<code>RunBanksy()</code> 後再 RunPCA + FindClusters 即可，多平台支援。",
    exp_en:"Seurat v5 has BANKSY built in: <code>RunBanksy()</code> then RunPCA + FindClusters — supported across platforms." },
  { type:"single",
    stem:"在 ST 流程中，HVG 與 SVG 的實務建議是？",
    stem_en:"In an ST workflow, the practical advice for HVG vs SVG is?",
    A:"初次分析用 HVG 做 PCA；針對空間結構分群時改用 SVG 重做 PCA 通常更乾淨", A_en:"Use HVGs for initial PCA; switch to SVGs for spatial-structure clustering for cleaner results",
    B:"絕對不能用 HVG", B_en:"Never use HVGs",
    C:"絕對不能用 SVG", C_en:"Never use SVGs",
    D:"兩者結果一定相同", D_en:"They always give identical results",
    ans:"A",
    exp:"實務上先用 HVG 快速探索，要凸顯空間結構時再用 SVG 重跑 PCA + clustering 通常更乾淨。",
    exp_en:"In practice: explore quickly with HVGs, then re-run PCA + clustering with SVGs for cleaner spatial-structure clusters." },
  { type:"tf",
    stem:"是非題：UMAP 上兩個 cluster 距離近就代表它們在組織上相鄰。",
    stem_en:"True/False: Two clusters close in UMAP must be spatially adjacent in tissue.",
    ans:"F",
    exp:"UMAP 表達相似度，與「組織上的物理距離」沒有直接關聯。要看空間鄰接得用 spatial plot 或 niche / CN 分析。",
    exp_en:"UMAP shows expression similarity, not physical distance in tissue. Use spatial plots or niche / CN analysis to assess adjacency." }
],

"Step 6：空間區域辨識 (Spatial Domains)": [
  { type:"single",
    stem:"為什麼 spatial domain 不能用 scRNA cluster 取代？",
    stem_en:"Why can't spatial domains simply be replaced by scRNA clusters?",
    A:"因為 scRNA 沒有基因", A_en:"scRNA has no genes",
    B:"因為 cluster 數不能控制", C_en:"Cluster count can't be controlled", B_en:"Cluster count can't be controlled",
    C:"因為相同細胞類型在不同空間區域可能有不同功能", C_en:"Same cell type can play different roles in different regions",
    D:"因為 ST 沒有 cluster", D_en:"ST has no clusters",
    ans:"C",
    exp:"Spatial domain 強調「表達相似 + 空間連續」雙重條件；同一 cell type 在不同 niche 可能行使不同功能，cell type 取代不了 spatial domain。",
    exp_en:"Spatial domains require both expression similarity and spatial contiguity. The same cell type can perform different functions across niches, so cell types alone cannot replace domains." },
  { type:"single",
    stem:"2025 NAR benchmark 中，Visium 上整體表現最佳的 spatial domain 工具是？",
    stem_en:"Best-performing spatial domain method on Visium in the 2025 NAR benchmark?",
    A:"GraphST", A_en:"GraphST",
    B:"K-means", B_en:"K-means",
    C:"PCA", C_en:"PCA",
    D:"tSNE", D_en:"tSNE",
    ans:"A",
    exp:"2025 NAR benchmark 在 Visium 平台上 GraphST 平均 ARI 0.55 居首，BayesSpace、SpaGCN、STAGATE 緊隨。",
    exp_en:"In the 2025 NAR benchmark on Visium, GraphST topped with mean ARI 0.55, followed by BayesSpace, SpaGCN, and STAGATE." },
  { type:"single",
    stem:"SpaGCN 跟其他方法最特別的不同是？",
    stem_en:"What is unique about SpaGCN?",
    A:"它不是 GNN", A_en:"It is not a GNN",
    B:"它把 H&E 影像顏色當成節點特徵", B_en:"It uses H&E image color as node features",
    C:"它只能用在 Stereo-seq", C_en:"It only works on Stereo-seq",
    D:"它只用 R", D_en:"It only runs in R",
    ans:"B",
    exp:"SpaGCN 把 H&E 顏色融入 graph 節點特徵，跟其他單純用 expression + position 的 GNN 方法不同；在 Stereo-seq 表現也很好。",
    exp_en:"SpaGCN integrates H&E color into graph node features, distinguishing it from purely expression+position GNN approaches; strong on Stereo-seq." },
  { type:"multi",
    stem:"下列哪些是常見的 spatial domain 識別方法？（多選）",
    stem_en:"Which are common spatial domain identification methods? (Multiple)",
    A:"BayesSpace", A_en:"BayesSpace",
    B:"SpaGCN", B_en:"SpaGCN",
    C:"GraphST", C_en:"GraphST",
    D:"BLAST", D_en:"BLAST",
    ans:["A","B","C"],
    exp:"前三者都是 spatial domain 工具。BLAST 是序列比對。",
    exp_en:"The first three are spatial domain tools. BLAST is for sequence alignment." },
  { type:"tf",
    stem:"是非題：Slide-seqV2 與 STARmap 上所有 spatial domain 方法的 ARI 都顯著低於 Visium。",
    stem_en:"True/False: All spatial domain methods show notably lower ARI on Slide-seqV2 / STARmap than on Visium.",
    ans:"T",
    exp:"2025 NAR benchmark 顯示 STARmap 與 Slide-seqV2 上所有方法表現皆顯著下降（最佳僅 ARI 0.31 / 0.15 範圍），需要謹慎詮釋。",
    exp_en:"The 2025 NAR benchmark shows all methods drop noticeably on STARmap / Slide-seqV2 (best ARI ~0.31 / 0.15) — interpret with care." },
  { type:"single",
    stem:"BayesSpace 的核心建模思路是？",
    stem_en:"BayesSpace's core modeling idea is?",
    A:"Bayesian + Markov Random Field 強制空間連續", A_en:"Bayesian + Markov Random Field to enforce spatial smoothness",
    B:"GNN + 對比學習", B_en:"GNN + contrastive learning",
    C:"K-means + UMAP", C_en:"K-means + UMAP",
    D:"deep learning autoencoder", D_en:"Deep learning autoencoder",
    ans:"A",
    exp:"BayesSpace 用 Bayesian + MRF 平滑空間 cluster，特別適合 Visium / 原始 ST。",
    exp_en:"BayesSpace uses Bayesian + MRF to enforce spatial smoothness — especially suited to Visium / original ST." },
  { type:"single",
    stem:"關於 image-based 平台（Xenium / MERFISH）做「空間區域分析」的常見做法？",
    stem_en:"For image-based platforms (Xenium / MERFISH), the common spatial-region analysis approach is?",
    A:"先 segmentation → cluster 細胞 → 再做 niche / CN 分析", A_en:"Segment → cluster cells → then niche / CN analysis",
    B:"直接套 BayesSpace", B_en:"Directly apply BayesSpace",
    C:"完全不需要分群", C_en:"No clustering needed",
    D:"只能做 PCA", D_en:"Only PCA",
    ans:"A",
    exp:"image-based 平台已是單細胞解析，傳統 spatial domain 不一定適用；通常 segmentation → 細胞分群 → niche/CN 是更合理的路線。",
    exp_en:"Image-based platforms are already single-cell. Classic spatial domain methods don't always apply; segment → cluster cells → niche/CN is more natural." },
  { type:"single",
    stem:"關於選方法，下列何者較接近 2025 benchmark 結論？",
    stem_en:"Which is closest to the 2025 benchmark conclusion about method selection?",
    A:"沒有任何方法在所有平台都最佳，平台是關鍵變數", A_en:"No method is best on every platform; platform is a key variable",
    B:"BayesSpace 永遠最佳", B_en:"BayesSpace is always best",
    C:"SpaGCN 永遠最佳", C_en:"SpaGCN is always best",
    D:"K-means 跟 GNN 表現差不多", D_en:"K-means and GNN perform similarly",
    ans:"A",
    exp:"benchmark 顯示 Visium → GraphST/BayesSpace；Stereo-seq → SpaGCN/Louvain；STARmap/Slide-seqV2 → 都不夠好。沒有 universal winner。",
    exp_en:"Benchmark shows Visium → GraphST/BayesSpace; Stereo-seq → SpaGCN/Louvain; STARmap/Slide-seqV2 → all weak. No universal winner." },
  { type:"tf",
    stem:"是非題：Visium HD 上 BayesSpace 通常是首選。",
    stem_en:"True/False: BayesSpace is usually the first choice on Visium HD.",
    ans:"F",
    exp:"BayesSpace 對 HD 的尺寸不友善，HD 通常用 BANKSY（Seurat v5 內建）或 sketching + Leiden。",
    exp_en:"BayesSpace doesn't scale well to HD size; HD typically uses BANKSY (built into Seurat v5) or sketching + Leiden." }
],

"Step 7：空間變異基因 (SVGs)": [
  { type:"single",
    stem:"「Highly Variable Gene」一定是 SVG 嗎？",
    stem_en:"Are HVGs always SVGs?",
    A:"是，兩者等同", A_en:"Yes, they are equivalent",
    B:"是，HVG 一定有空間結構", B_en:"Yes, HVGs always have spatial structure",
    C:"不一定，HVG 變異可能是雜訊也可能跨整片組織分散", C_en:"Not necessarily — high variance can be noise or distributed without structure",
    D:"反過來才對 (SVG 一定是 HVG)", D_en:"The reverse holds (SVG ⊂ HVG)",
    ans:"C",
    exp:"HVG 只看整體變異；SVG 要求變異跟空間自相關。可能是 HVG 但完全 random、不是 SVG。",
    exp_en:"HVGs care only about overall variance; SVGs require spatial autocorrelation. A gene can be HVG yet random, not an SVG." },
  { type:"single",
    stem:"2025 Genome Biology benchmark 中速度與準確度都領先的 SVG 工具是？",
    stem_en:"Best speed-accuracy SVG tool in the 2025 Genome Biology benchmark?",
    A:"SPARK-X", A_en:"SPARK-X",
    B:"SpatialDE (原版)", B_en:"SpatialDE (original)",
    C:"K-means", C_en:"K-means",
    D:"Linear regression", D_en:"Linear regression",
    ans:"A",
    exp:"SPARK-X 平均相關 0.88、速度也快；SpatialDE2 0.81、nnSVG 0.80；Moran's I 0.76 為強大基線。",
    exp_en:"SPARK-X reaches avg correlation 0.88 with great speed; SpatialDE2 0.81; nnSVG 0.80; Moran's I 0.76 as a strong baseline." },
  { type:"single",
    stem:"Moran's I 的核心概念是？",
    stem_en:"Core idea of Moran's I?",
    A:"計算每個基因的平均表達", A_en:"Computes mean expression",
    B:"量化「鄰近 spot 的表達是否比隨機更相似」", B_en:"Quantifies whether neighbors' expressions are more similar than random",
    C:"自動估算 cluster 數", C_en:"Estimates cluster count",
    D:"跟空間無關", D_en:"Has nothing to do with space",
    ans:"B",
    exp:"Moran's I 是經典空間自相關統計，比較每個位置與其鄰居的加權相似度。",
    exp_en:"Moran's I is the classical spatial autocorrelation statistic, comparing each location with weighted neighbor similarity." },
  { type:"multi",
    stem:"下列哪些屬於 SVG 識別方法？（多選）",
    stem_en:"Which are SVG identification methods? (Multiple)",
    A:"SpatialDE / SpatialDE2", A_en:"SpatialDE / SpatialDE2",
    B:"SPARK / SPARK-X", B_en:"SPARK / SPARK-X",
    C:"nnSVG", C_en:"nnSVG",
    D:"BLAST", D_en:"BLAST",
    ans:["A","B","C"],
    exp:"前三者皆為 SVG 工具。BLAST 為序列比對。",
    exp_en:"The first three are SVG tools. BLAST is for sequence alignment." },
  { type:"tf",
    stem:"是非題：在 2025 systematic benchmark 中，Moran's I 雖然簡單但表現仍可作為強大基線（mean correlation ~0.76）。",
    stem_en:"True/False: In the 2025 systematic benchmark, Moran's I, though simple, remains a strong baseline (mean correlation ~0.76).",
    ans:"T",
    exp:"Moran's I 平均相關 0.76 雖低於 SPARK-X 但仍排前列，且速度極快、Squidpy 內建。",
    exp_en:"Moran's I averages 0.76 — below SPARK-X but still top-tier, plus very fast and built into Squidpy." },
  { type:"single",
    stem:"關於 SPARK-X 的計算特色，下列何者較正確？",
    stem_en:"About SPARK-X's computational character, which is closer?",
    A:"使用 multi-kernel non-parametric 檢定，速度快且 scalable", A_en:"Multi-kernel non-parametric test, fast and scalable",
    B:"是 deep learning 模型", B_en:"It's a deep learning model",
    C:"只能跑在小資料", C_en:"Only runs on small data",
    D:"完全不考慮空間", D_en:"Ignores space entirely",
    ans:"A",
    exp:"SPARK-X 使用 multi-kernel non-parametric 框架，記憶體/速度皆優，適合大型 ST。",
    exp_en:"SPARK-X uses a multi-kernel non-parametric framework with great memory/speed, suited for large ST datasets." },
  { type:"single",
    stem:"關於 nnSVG 的特色，下列何者較正確？",
    stem_en:"About nnSVG's character, which is closer?",
    A:"使用 nearest-neighbor Gaussian Process，可 scale 到大資料", A_en:"Uses nearest-neighbor Gaussian Processes; scalable to large data",
    B:"是 NMF-based 方法", B_en:"It's an NMF-based method",
    C:"完全不能解釋 lengthscale", C_en:"Cannot interpret lengthscale at all",
    D:"只能跑單樣本", D_en:"Only runs on single samples",
    ans:"A",
    exp:"nnSVG 用 nearest-neighbor GP 提升 scalability，可估 lengthscale 解釋空間結構。",
    exp_en:"nnSVG uses nearest-neighbor GPs for scalability and can estimate lengthscale to interpret spatial structure." },
  { type:"multi",
    stem:"關於選 SVG 方法的實務建議，下列何者較合理？（多選）",
    stem_en:"Practical advice for choosing SVG methods? (Multiple)",
    A:"大資料 → SPARK-X", A_en:"Large data → SPARK-X",
    B:"想看 lengthscale 結構 → nnSVG", B_en:"Want lengthscale → nnSVG",
    C:"想要解釋直觀 + 速度極快 → Moran's I (Squidpy 內建)", C_en:"Intuitive + very fast → Moran's I (built into Squidpy)",
    D:"小資料時應該完全避免任何 SVG 方法", D_en:"Avoid SVG methods entirely on small data",
    ans:["A","B","C"],
    exp:"A、B、C 都是合理建議；D 錯誤——小資料反而方法選擇限制較少。",
    exp_en:"A, B, C are reasonable. D is wrong — small data has fewer method constraints." },
  { type:"tf",
    stem:"是非題：實務上常將 Moran's I 與 SPARK-X / nnSVG 並列輸出取交集，比單一方法更可靠。",
    stem_en:"True/False: In practice, intersecting outputs of Moran's I with SPARK-X / nnSVG is more reliable than a single method.",
    ans:"T",
    exp:"不同方法對不同 spatial pattern 敏感度不同，多方法取交集（或 union 後手動 prioritize）能降低偏差。",
    exp_en:"Different methods are sensitive to different patterns; intersecting (or union + manual prioritization) reduces bias." }
],

"Step 8：細胞類型解卷積 (Deconvolution)": [
  { type:"single",
    stem:"一個 spot 涵蓋的細胞類型沒出現在 reference 裡，會發生什麼？",
    stem_en:"What if a spot's true cell type is missing from the reference?",
    A:"演算法自動發現新類型", A_en:"The algorithm discovers a new type automatically",
    B:"演算法自動報錯", B_en:"The algorithm errors out",
    C:"它會被分配到 reference 中最相似的類型 → 假陽性", C_en:"It is allocated to the most similar reference type → false positives",
    D:"spot 會被刪除", D_en:"The spot is removed",
    ans:"C",
    exp:"deconvolution 只能輸出 reference 中存在的細胞類型；缺類型 → 強制分到最相似類型 → 假陽性。",
    exp_en:"Deconvolution can only output cell types present in the reference. Missing types are forced into the nearest type → false positives." },
  { type:"single",
    stem:"想要 CPU-only、快速、且穩定的 deconvolution 起點，建議？",
    stem_en:"CPU-only, fast, robust starting point for deconvolution?",
    A:"RCTD", A_en:"RCTD",
    B:"cell2location", B_en:"cell2location",
    C:"Tangram", C_en:"Tangram",
    D:"STdeconvolve", D_en:"STdeconvolve",
    ans:"A",
    exp:"RCTD CPU 平行、速度快、benchmark 表現穩定，是入門首選。cell2location 通常需要 GPU。",
    exp_en:"RCTD is CPU-parallel, fast, benchmark-stable — the recommended starting point. cell2location typically needs a GPU." },
  { type:"single",
    stem:"cell2location 跟 RCTD 主要輸出的差別？",
    stem_en:"Key output difference between cell2location and RCTD?",
    A:"兩者都輸出細胞數", A_en:"Both output cell counts",
    B:"cell2location 輸出 abundance；RCTD 多輸出 proportion", B_en:"cell2location outputs abundance; RCTD typically outputs proportions",
    C:"兩者完全一樣", C_en:"They are identical",
    D:"cell2location 只能 R 用", D_en:"cell2location is R-only",
    ans:"B",
    exp:"cell2location 給 abundance（每 spot 細胞數估值）；RCTD/SPOTlight 通常給比例 (proportion)。下游 marker correlate 時需區分。",
    exp_en:"cell2location outputs abundance (cells per spot); RCTD/SPOTlight typically output proportions. Distinguish when correlating with markers downstream." },
  { type:"single",
    stem:"關於 reference 選擇，下列何者較合理？",
    stem_en:"Regarding reference choice, which is more reasonable?",
    A:"任何 scRNA reference 都可以使用", A_en:"Any scRNA reference works",
    B:"reference 應來自相似組織，否則結果不可靠", B_en:"Reference should come from similar tissue; otherwise unreliable",
    C:"reference 越大越好，組織不重要", C_en:"Bigger reference is always better; tissue doesn't matter",
    D:"完全不需要 reference", D_en:"No reference is needed",
    ans:"B",
    exp:"reference 必須跟 ST 樣本組織相符；用心臟 reference 解腦切片是災難。",
    exp_en:"Reference must match the ST tissue. Using a heart reference on a brain section is a disaster." },
  { type:"multi",
    stem:"下列哪些是 ST deconvolution 工具？（多選）",
    stem_en:"Which are ST deconvolution tools? (Multiple)",
    A:"cell2location", A_en:"cell2location",
    B:"RCTD", B_en:"RCTD",
    C:"CARD", C_en:"CARD",
    D:"DESeq2", D_en:"DESeq2",
    ans:["A","B","C"],
    exp:"前三者皆為 deconvolution 工具。DESeq2 是 bulk RNA-seq DE 工具。",
    exp_en:"The first three are deconvolution tools. DESeq2 is for bulk RNA-seq DE." },
  { type:"tf",
    stem:"是非題：cell2location 對於 reference 中比例 < 1% 的稀有細胞容易被 zero-out。",
    stem_en:"True/False: cell2location can easily zero-out rare cell types (< 1% of reference).",
    ans:"T",
    exp:"概率方法對極稀有細胞 prior 偏低，容易抓不到。實務可調 N_cells_per_location 較高，或用 Tangram 直接 mapping 互相驗證。",
    exp_en:"Probabilistic methods give rare cells low prior and easily miss them. In practice, raise N_cells_per_location or cross-check with Tangram cell mapping." },
  { type:"single",
    stem:"關於 STdeconvolve 的特色，下列何者較正確？",
    stem_en:"About STdeconvolve, which is closer?",
    A:"它是 reference-free 方法，不需要外部 scRNA reference", A_en:"It is reference-free, requiring no external scRNA reference",
    B:"它必須要有 reference", B_en:"It requires a reference",
    C:"它只能用在 image-based 平台", C_en:"It only works on image-based platforms",
    D:"它取代 PCA", D_en:"It replaces PCA",
    ans:"A",
    exp:"STdeconvolve 用 LDA 做 reference-free deconvolution，特別適合沒有合適 scRNA reference 的場景，如稀有組織。",
    exp_en:"STdeconvolve uses LDA for reference-free deconvolution — useful when no suitable scRNA reference exists (e.g., rare tissues)." },
  { type:"single",
    stem:"2023 Nat Comm benchmark 中，Visium 上整體前列的 deconvolution 方法是？",
    stem_en:"Top deconvolution methods on Visium in the 2023 Nat Comm benchmark?",
    A:"CARD / cell2location / Tangram 居前列", A_en:"CARD / cell2location / Tangram lead",
    B:"PCA / UMAP / Leiden", B_en:"PCA / UMAP / Leiden",
    C:"BLAST", C_en:"BLAST",
    D:"DESeq2", D_en:"DESeq2",
    ans:"A",
    exp:"2023 Nat Comm benchmark 顯示 CARD、cell2location、Tangram 在 Visium 上整體排名前列。",
    exp_en:"The 2023 Nat Comm benchmark ranks CARD, cell2location, and Tangram at the top on Visium." },
  { type:"multi",
    stem:"下列哪些是減輕「reference 不完整 / 稀有細胞 zero-out」的策略？（多選）",
    stem_en:"Which mitigate 'incomplete reference / rare-cell zero-out'? (Multiple)",
    A:"提高 cell2location 的 N_cells_per_location", A_en:"Raise cell2location's N_cells_per_location",
    B:"用 Tangram 把 sc cells 直接映射觀察", B_en:"Use Tangram to map sc cells directly",
    C:"驗證稀有 marker 的 spatial pattern", C_en:"Validate rare-cell markers' spatial patterns",
    D:"刪除所有稀有細胞 reference", D_en:"Delete all rare-cell references",
    ans:["A","B","C"],
    exp:"A、B、C 是合理 mitigation；D 適得其反。",
    exp_en:"A, B, C are reasonable mitigations; D is counterproductive." },
  { type:"tf",
    stem:"是非題：spot-based ST 必須做 deconvolution 才能討論 cell type；image-based ST 通常不需要。",
    stem_en:"True/False: spot-based ST requires deconvolution to discuss cell types; image-based ST usually does not.",
    ans:"T",
    exp:"spot-based 一個 spot 多細胞，必須拆解。image-based 已是單細胞解析度，segmentation + clustering 即可。",
    exp_en:"Spot-based has multi-cell spots requiring deconvolution. Image-based is single-cell, only needing segmentation + clustering." }
],

"Step 9：與 scRNA-seq 整合 (scInteg)": [
  { type:"single",
    stem:"下列哪個工具最適合「想要單細胞解析的空間圖」？",
    stem_en:"Which tool best fits 'I want a single-cell-resolution spatial map'?",
    A:"RCTD", A_en:"RCTD",
    B:"cell2location", B_en:"cell2location",
    C:"CytoSPACE", C_en:"CytoSPACE",
    D:"Moran's I", D_en:"Moran's I",
    ans:"C",
    exp:"CytoSPACE 把 sc cell 一對一映射到 ST spot，達單細胞解析空間圖；deconvolution 工具給比例而非單細胞。",
    exp_en:"CytoSPACE assigns sc cells one-to-one to ST spots, yielding single-cell spatial maps; deconvolution gives proportions, not single cells." },
  { type:"single",
    stem:"Tangram 除了 cell mapping 還能做？",
    stem_en:"Beyond cell mapping, Tangram also performs?",
    A:"基因 imputation（補齊未被測到的基因）", A_en:"Gene imputation (fill in untested genes)",
    B:"自動 segmentation", B_en:"Automatic segmentation",
    C:"估算 ligand-receptor", C_en:"Ligand-receptor inference",
    D:"移除 batch effect", D_en:"Removes batch effects",
    ans:"A",
    exp:"Tangram 的 project_genes 可以同時做 imputation——尤其對 image-based panel 補上未測基因很有用。",
    exp_en:"Tangram's project_genes also imputes — especially useful to fill off-panel genes for image-based data." },
  { type:"single",
    stem:"Tangram 訓練基因怎麼挑最有效率？",
    stem_en:"How to pick training genes for Tangram efficiently?",
    A:"全部基因都丟進去", A_en:"Pass in all genes",
    B:"每個細胞類型各取 top markers (共 ~1k)", B_en:"Top markers per cell type (~1k total)",
    C:"隨機取 100 個", C_en:"Random 100 genes",
    D:"只用 housekeeping 基因", D_en:"Only housekeeping genes",
    ans:"B",
    exp:"Tangram 推薦用 top 1k unique markers stratified by cell-type 作 training set，效率與穩定性最佳。",
    exp_en:"Tangram recommends top 1k unique markers stratified by cell type for training — best efficiency and stability." },
  { type:"multi",
    stem:"下列哪些是 sc-Spatial 整合常用方法？（多選）",
    stem_en:"Which are common sc-Spatial integration methods? (Multiple)",
    A:"Tangram", A_en:"Tangram",
    B:"CytoSPACE", C_en:"CytoSPACE", B_en:"CytoSPACE",
    C:"Seurat label transfer (FindTransferAnchors)", C_en:"Seurat label transfer (FindTransferAnchors)",
    D:"Cellpose", D_en:"Cellpose",
    ans:["A","B","C"],
    exp:"前三者都是 sc–ST 整合工具。Cellpose 是 segmentation 工具。",
    exp_en:"The first three are sc–ST integration tools. Cellpose is for segmentation." },
  { type:"tf",
    stem:"是非題：CytoSPACE 比 deconvolution 多做的事，是「one-to-one assignment」。",
    stem_en:"True/False: What CytoSPACE adds beyond deconvolution is 'one-to-one assignment'.",
    ans:"T",
    exp:"CytoSPACE 把每顆 sc cell 個別映射到 ST 上的 spot/位置，做出單細胞解析地圖；deconvolution 只給比例。",
    exp_en:"CytoSPACE assigns each sc cell individually to a spot/location, yielding a single-cell map; deconvolution only gives proportions." },
  { type:"single",
    stem:"想用 Seurat 做 label transfer 把 scRNA cell-type 投到 ST，最對應的函式是？",
    stem_en:"In Seurat, the function for label transfer from scRNA to ST is?",
    A:"FindTransferAnchors() + TransferData()", A_en:"FindTransferAnchors() + TransferData()",
    B:"FindNeighbors()", B_en:"FindNeighbors()",
    C:"RunPCA()", C_en:"RunPCA()",
    D:"NormalizeData()", D_en:"NormalizeData()",
    ans:"A",
    exp:"Seurat label transfer 流程是 FindTransferAnchors → TransferData，把 reference cell-type 標籤投射到 query。",
    exp_en:"Seurat's label-transfer pipeline is FindTransferAnchors → TransferData, projecting reference cell-type labels onto the query." },
  { type:"single",
    stem:"實務上，做 sc-Spatial 整合的「驗證」步驟，下列何者最關鍵？",
    stem_en:"In practice, the most critical 'validation' step for sc-Spatial integration is?",
    A:"把 imputed marker 跟 ground-truth marker 比較，並看 spatial domain 是否符合解剖", A_en:"Compare imputed markers with ground-truth and verify spatial domains match anatomy",
    B:"完全不需要驗證", B_en:"No validation needed",
    C:"只需檢查 PCA 解釋變異", C_en:"Only check PCA explained variance",
    D:"重新跑 normalization", D_en:"Re-run normalization",
    ans:"A",
    exp:"sanity check：imputed marker 與真實 marker 對比 + 空間 domain 是否符合已知解剖學是必要驗證。",
    exp_en:"Sanity check: compare imputed vs ground-truth markers and verify spatial domains match known anatomy." },
  { type:"single",
    stem:"關於 Tangram 在 Visium 上的常用設定，下列何者較合理？",
    stem_en:"On Visium, a reasonable Tangram setting is?",
    A:"使用 constrained mode 並提供每 spot 細胞數估計", A_en:"Use constrained mode with per-spot cell-count estimates",
    B:"關閉所有約束", B_en:"Turn off all constraints",
    C:"完全不需要 marker 訓練", C_en:"No marker training needed",
    D:"必須是 single-cell 平台才能跑", D_en:"Only works on single-cell platforms",
    ans:"A",
    exp:"Visium 因為一 spot 多細胞，Tangram constrained mode（density_prior + cells/location）能讓映射更合理。",
    exp_en:"Because Visium has multi-cell spots, Tangram's constrained mode (density_prior + cells/location) yields more sensible mapping." }
],

"Step 10：空間細胞通訊 (CCC)": [
  { type:"single",
    stem:"CellChat v2 spatial 與 v1 的核心差別？",
    stem_en:"Key difference between CellChat v2 spatial and v1?",
    A:"v2 不再支援 scRNA", A_en:"v2 no longer supports scRNA",
    B:"v2 可以把空間距離納入 LR 推論", B_en:"v2 incorporates spatial distance into LR inference",
    C:"v2 不需要 ligand", C_en:"v2 doesn't need ligands",
    D:"兩者完全相同", D_en:"They are identical",
    ans:"B",
    exp:"CellChat v2 引入 spatial mode，可只計「物理鄰近 cluster pair」的 LR 互動，避免 scRNA 模式下無視距離的全組織配對。",
    exp_en:"CellChat v2 adds spatial mode, restricting LR inference to physically adjacent cluster pairs — avoiding scRNA's distance-blind whole-tissue pairing." },
  { type:"single",
    stem:"想要研究「一個 ligand 同時被多個受體競爭」的情境，最適合？",
    stem_en:"Best choice for 'one ligand competed for by multiple receptors'?",
    A:"CellPhoneDB", A_en:"CellPhoneDB",
    B:"Seurat anchors", B_en:"Seurat anchors",
    C:"COMMOT (collective optimal transport)", C_en:"COMMOT (collective optimal transport)",
    D:"Moran's I", D_en:"Moran's I",
    ans:"C",
    exp:"COMMOT 用 collective optimal transport 一次解多 ligand vs 多 receptor 的「運輸方案」，特別適合競爭情境。",
    exp_en:"COMMOT uses collective optimal transport to jointly solve many-ligand vs many-receptor 'transport plans' — ideal for competition scenarios." },
  { type:"single",
    stem:"NicheNet 在 spatial 流程裡的典型角色？",
    stem_en:"Typical role of NicheNet in a spatial pipeline?",
    A:"接在 spatial CCC 之後，回追 LR 下游 target gene 與訊號路徑", A_en:"After spatial CCC, traces LR's downstream targets and signaling pathways",
    B:"取代 deconvolution", B_en:"Replaces deconvolution",
    C:"取代 spatial domain identification", C_en:"Replaces spatial domain identification",
    D:"做 segmentation", D_en:"Performs segmentation",
    ans:"A",
    exp:"NicheNet 把 LR → 下游 target gene 連起來；常用於 CellChat/COMMOT 找出 LR pair 後的「故事完成」。",
    exp_en:"NicheNet links LR to downstream target genes — used to complete the story after CellChat/COMMOT identifies LR pairs." },
  { type:"multi",
    stem:"下列哪些是空間感知 CCC 工具？（多選）",
    stem_en:"Which are spatially-aware CCC tools? (Multiple)",
    A:"CellChat v2 (spatial mode)", A_en:"CellChat v2 (spatial mode)",
    B:"COMMOT", B_en:"COMMOT",
    C:"SpaTalk", C_en:"SpaTalk",
    D:"Cellpose", D_en:"Cellpose",
    ans:["A","B","C"],
    exp:"前三者皆為空間感知 CCC 工具。Cellpose 是 segmentation。",
    exp_en:"The first three are spatially-aware CCC tools. Cellpose is for segmentation." },
  { type:"tf",
    stem:"是非題：scRNA 版的 CellPhoneDB 假設「同 cluster 內所有細胞都可能跟另一 cluster 全部細胞互動」。",
    stem_en:"True/False: scRNA's CellPhoneDB assumes all cells in cluster A may interact with all cells in cluster B.",
    ans:"T",
    exp:"scRNA 失去座標，CellPhoneDB / CellChat v1 都做「全組織配對」，這是空間 CCC 改進的痛點。",
    exp_en:"Without coordinates, CellPhoneDB / CellChat v1 perform whole-tissue pairing — exactly what spatial CCC improves." },
  { type:"single",
    stem:"在 Visium 上跑 CellChat v2 spatial，<code>scale.distance</code> 預設值通常是？",
    stem_en:"Running CellChat v2 spatial on Visium, the default <code>scale.distance</code> is typically?",
    A:"0.01（針對 Visium 55 µm spot 校正）", A_en:"0.01 (calibrated for Visium 55 µm spot)",
    B:"100", B_en:"100",
    C:"完全沒有預設值", C_en:"No default exists",
    D:"1000", D_en:"1000",
    ans:"A",
    exp:"CellChat v2 spatial 的 scale.distance = 0.01 是針對 Visium spot 大小校正；其他平台應依 spot 距離 scale。",
    exp_en:"CellChat v2's scale.distance = 0.01 is calibrated for Visium spots; other platforms should rescale by spot distance." },
  { type:"single",
    stem:"image-based 平台 (Xenium / MERFISH) 上做 CCC 的優勢是？",
    stem_en:"What's the advantage of CCC on image-based platforms (Xenium / MERFISH)?",
    A:"單細胞解析度，能直接做 cell-level 互動推論", A_en:"Single-cell resolution allows direct cell-level interaction inference",
    B:"完全不需要 ligand-receptor 配對", B_en:"No need for ligand-receptor pairing",
    C:"必須先做 deconvolution", C_en:"Must do deconvolution first",
    D:"只能用 R", D_en:"R-only",
    ans:"A",
    exp:"image-based 已是單細胞，可直接 cell-by-cell 比鄰接 LR；spot-based 還得先 deconvolution 才能跨類型推論。",
    exp_en:"Image-based is already single-cell, so LR can be tested cell-by-cell; spot-based first needs deconvolution before cross-type inference." },
  { type:"tf",
    stem:"是非題：傳統 scRNA 的 CCC 工具（CellPhoneDB / CellChat v1）也可以直接套到 ST，不會有任何問題。",
    stem_en:"True/False: Classic scRNA CCC tools (CellPhoneDB / CellChat v1) can be applied to ST without issue.",
    ans:"F",
    exp:"它們忽略距離，會給「跨整片組織配對」的不真實結果。空間 CCC 必須用 v2 spatial / COMMOT 等工具。",
    exp_en:"They ignore distance and yield unrealistic 'whole-tissue pairings'. Use spatial-aware tools like CellChat v2 / COMMOT." }
],

"Step 11：生態棲位 (Niche)": [
  { type:"single",
    stem:"Spatial domain 與 niche 最關鍵差別？",
    stem_en:"Most important distinction between spatial domain and niche?",
    A:"niche 不需要空間資訊", A_en:"Niche doesn't need spatial info",
    B:"domain 看自己 expression；niche 看周遭鄰居組成", B_en:"Domain looks at one's own expression; niche looks at surrounding neighbors",
    C:"兩者完全相同", C_en:"They are identical",
    D:"niche 不能用 GNN", D_en:"Niche can't use GNNs",
    ans:"B",
    exp:"Spatial domain 看「我自己」表達什麼；niche 看「我的鄰居」是誰。同一 T cell 在不同 niche 可能行使不同功能。",
    exp_en:"Spatial domain = 'what I express'; niche = 'who is around me'. The same T cell may play different roles in different niches." },
  { type:"single",
    stem:"想要快速、零成本看「哪兩個 cluster 比隨機更常相鄰」，最方便？",
    stem_en:"Quickest, zero-cost way to ask 'which two clusters are adjacent more than chance'?",
    A:"CellCharter", A_en:"CellCharter",
    B:"NicheCompass", B_en:"NicheCompass",
    C:"Squidpy nhood_enrichment", C_en:"Squidpy nhood_enrichment",
    D:"SpatialDE", D_en:"SpatialDE",
    ans:"C",
    exp:"Squidpy 的 sq.gr.nhood_enrichment 一行就能做 permutation 檢定，是最簡單入門。",
    exp_en:"Squidpy's sq.gr.nhood_enrichment runs a permutation test in one line — the simplest entry point." },
  { type:"single",
    stem:"NicheCompass 的特色？",
    stem_en:"What distinguishes NicheCompass?",
    A:"把 signaling pathway 知識當 prior 嵌入模型", A_en:"Embeds signaling-pathway priors into the model",
    B:"不需 spatial 資訊", B_en:"Needs no spatial info",
    C:"只支援 R", C_en:"R-only",
    D:"取代 deconvolution", D_en:"Replaces deconvolution",
    ans:"A",
    exp:"NicheCompass 用已知 pathway 做 prior，學出來的 niche 帶 pathway-level 解釋。",
    exp_en:"NicheCompass uses pathway knowledge as prior, producing niches with pathway-level interpretability." },
  { type:"multi",
    stem:"下列哪些屬於 niche / microenvironment 分析工具？（多選）",
    stem_en:"Which are niche / microenvironment tools? (Multiple)",
    A:"CellCharter", A_en:"CellCharter",
    B:"NicheCompass", B_en:"NicheCompass",
    C:"scNiche", C_en:"scNiche",
    D:"SoupX", D_en:"SoupX",
    ans:["A","B","C"],
    exp:"前三者皆為 niche 工具。SoupX 是 scRNA ambient RNA 移除工具。",
    exp_en:"The first three are niche tools. SoupX is for ambient RNA removal in scRNA." },
  { type:"tf",
    stem:"是非題：CN (Cellular Neighborhood) 的概念源自 CODEX / MIBI 等 multiplex imaging 平台，核心思路與 niche 相通。",
    stem_en:"True/False: 'Cellular Neighborhood (CN)' originated from CODEX / MIBI multiplex imaging and shares the core idea with niche.",
    ans:"T",
    exp:"CN 是免疫學影像平台用語，與 niche 同義；都看每個細胞的鄰居組成。",
    exp_en:"CN is the term used in immunology imaging platforms; it's synonymous with niche — both consider each cell's neighbor composition." },
  { type:"single",
    stem:"CellCharter 的核心建模思路？",
    stem_en:"CellCharter's core modeling idea?",
    A:"在 spatial graph 學 latent embedding，用 GMM 找 niche", A_en:"Learn latent embeddings on a spatial graph, then GMM to find niches",
    B:"PCA + K-means", B_en:"PCA + K-means",
    C:"是 deconvolution 工具", C_en:"It is a deconvolution tool",
    D:"是 segmentation 工具", D_en:"It is a segmentation tool",
    ans:"A",
    exp:"CellCharter 在 spatial graph 學 embedding 再以 GMM 群集成 niche，支援 multi-omics。",
    exp_en:"CellCharter learns spatial-graph embeddings then GMM-clusters to find niches; supports multi-omics." },
  { type:"single",
    stem:"在 image-based ST（Xenium / MERFISH）上做 niche 分析的典型流程？",
    stem_en:"Typical niche analysis flow on image-based ST (Xenium / MERFISH)?",
    A:"先 segmentation → cluster cells → 建 spatial graph → 計算 CN vector → cluster CN vector", A_en:"Segment → cluster cells → build spatial graph → compute CN vectors → cluster CN vectors",
    B:"完全跳過 segmentation", B_en:"Skip segmentation entirely",
    C:"直接用 BayesSpace", C_en:"Directly use BayesSpace",
    D:"只看 expression 不需要 spatial", D_en:"Look at expression only, no spatial needed",
    ans:"A",
    exp:"image-based 流程：segmentation → 細胞分群 → spatial graph (k-NN/Delaunay) → 每細胞的鄰居組成向量 → cluster 該向量。",
    exp_en:"Image-based pipeline: segment → cluster cells → spatial graph (k-NN/Delaunay) → per-cell neighbor composition vector → cluster vectors." },
  { type:"tf",
    stem:"是非題：Seurat v5 的 BuildNicheAssay() 可以直接在 Visium / Xenium 上做 niche cluster。",
    stem_en:"True/False: Seurat v5's BuildNicheAssay() can perform niche clustering directly on Visium / Xenium.",
    ans:"T",
    exp:"Seurat v5 把 niche assay 內建，從 image FOV + cell type 一行即可建構並 cluster niche。",
    exp_en:"Seurat v5 ships BuildNicheAssay(), constructing and clustering niches in one line from image FOV + cell type." }
],

"Step 12：空間軌跡 (Trajectory)": [
  { type:"single",
    stem:"ST trajectory 跟 scRNA pseudotime 最大的不同？",
    stem_en:"Biggest difference between ST trajectory and scRNA pseudotime?",
    A:"ST 不能算 pseudotime", A_en:"ST cannot compute pseudotime",
    B:"ST 可以對應到實體空間軸（如離傷口距離）", B_en:"ST can map to a physical axis (e.g., distance to wound)",
    C:"scRNA 沒有 trajectory", C_en:"scRNA has no trajectory",
    D:"ST 不需要分群", D_en:"ST doesn't need clustering",
    ans:"B",
    exp:"ST 有天然的物理軸（距傷口、距血管、皮層深度），可以把 pseudotime 投回空間獲得真實軌跡解釋。",
    exp_en:"ST has natural physical axes (distance to wound, vessels, cortical depth), letting pseudotime project back into space for grounded interpretation." },
  { type:"single",
    stem:"ONTraC 的核心特色？",
    stem_en:"Defining feature of ONTraC?",
    A:"在 niche 層級畫出連續的微環境演進", A_en:"Continuous niche-level microenvironment trajectory",
    B:"取代 deconvolution", B_en:"Replaces deconvolution",
    C:"取代 segmentation", C_en:"Replaces segmentation",
    D:"取代 PCA", D_en:"Replaces PCA",
    ans:"A",
    exp:"ONTraC 用 GNN 在 niche 層級做空間連續軌跡，是 2025 Genome Biology 的方法。",
    exp_en:"ONTraC uses a GNN to construct niche-level continuous spatial trajectories — published in Genome Biology 2025." },
  { type:"single",
    stem:"SpaceFlow 主要的輸出是？",
    stem_en:"Main output of SpaceFlow?",
    A:"cell type 標籤", A_en:"Cell type labels",
    B:"ligand-receptor pair", B_en:"Ligand-receptor pairs",
    C:"pseudo-spatiotemporal map (pSM)", C_en:"Pseudo-spatiotemporal map (pSM)",
    D:"UMAP", D_en:"UMAP",
    ans:"C",
    exp:"SpaceFlow 結合 GNN + diffusion 計算 pSM，把 pseudotime 與空間結構同時表達。",
    exp_en:"SpaceFlow combines GNN + diffusion to produce a pSM, jointly representing pseudotime and spatial structure." },
  { type:"multi",
    stem:"下列哪些屬於 cell-level pseudotime 工具，可以在 ST 把結果投回空間？（多選）",
    stem_en:"Which are cell-level pseudotime tools that can project results back to space in ST? (Multiple)",
    A:"Monocle3", A_en:"Monocle3",
    B:"Slingshot", B_en:"Slingshot",
    C:"scVelo", C_en:"scVelo",
    D:"Cellpose", D_en:"Cellpose",
    ans:["A","B","C"],
    exp:"前三者都是 scRNA 起源的 trajectory 工具，事後可投回 ST。Cellpose 是 segmentation 工具。",
    exp_en:"The first three are scRNA-origin trajectory tools that can be projected back into ST. Cellpose is for segmentation." },
  { type:"tf",
    stem:"是非題：把 scRNA pseudotime 投回空間，一定能得到「空間連續」的軌跡。",
    stem_en:"True/False: Projecting scRNA pseudotime back to space always yields a spatially-continuous trajectory.",
    ans:"F",
    exp:"細胞狀態相似的兩細胞可能空間上很遠（如循環免疫細胞）；要驗證 spatial autocorrelation 才能談「空間連續」。",
    exp_en:"Two cells with similar states can be spatially distant (e.g., circulating immune cells); verify spatial autocorrelation before claiming continuity." },
  { type:"single",
    stem:"想要解讀「離血管多遠」這類連續性的細胞狀態漸變，下列何者較合理？",
    stem_en:"To interpret continuous state gradients like 'distance to vessel', the most reasonable approach is?",
    A:"先計算 pseudotime，並把結果投回空間 + 算 spatial autocorrelation 驗證連續性", A_en:"Compute pseudotime, project back to space, and verify continuity via spatial autocorrelation",
    B:"完全不做 pseudotime", B_en:"Skip pseudotime entirely",
    C:"只看 PCA", C_en:"Only PCA",
    D:"做 segmentation 即可", D_en:"Just segmentation",
    ans:"A",
    exp:"pseudotime 投回空間 + 用 Moran's I 等檢驗 spatial 連續性，是嚴謹的 ST trajectory 流程。",
    exp_en:"Project pseudotime back + use Moran's I to test spatial continuity is a rigorous ST trajectory workflow." },
  { type:"single",
    stem:"對於 niche-level trajectory，2025 領域中最具代表性的工具是？",
    stem_en:"Most representative niche-level trajectory tool in 2025?",
    A:"ONTraC", A_en:"ONTraC",
    B:"SoupX", B_en:"SoupX",
    C:"DoubletFinder", C_en:"DoubletFinder",
    D:"BLAST", D_en:"BLAST",
    ans:"A",
    exp:"ONTraC（2025 Genome Biology）是 niche-level trajectory 的代表方法。",
    exp_en:"ONTraC (2025 Genome Biology) is the representative niche-level trajectory tool." }
],

"Step 13：多樣本整合 (Multi-sample)": [
  { type:"single",
    stem:"PASTE 不適合用在哪一種情境？",
    stem_en:"When is PASTE NOT appropriate?",
    A:"同一個小鼠的連續腦切片", A_en:"Serial brain sections from one mouse",
    B:"同個樣本相鄰兩切片的 3D 重建", B_en:"3D reconstruction from adjacent slices of one sample",
    C:"不同個體 / 不同條件 / 幾何不相似的切片", C_en:"Different individuals / conditions / geometrically dissimilar slices",
    D:"取得 transport plan", D_en:"Computing the transport plan",
    ans:"C",
    exp:"PASTE 假設切片幾何相似，不適合不同個體 / 不同條件的情境，應改用 STAligner 或 STAIR。",
    exp_en:"PASTE assumes geometric similarity — unsuitable for different individuals / conditions. Use STAligner or STAIR instead." },
  { type:"single",
    stem:"2025 ST batch correction benchmark 顯示 Harmony 的特徵是？",
    stem_en:"According to the 2025 ST benchmark, Harmony tends to:",
    A:"batch correction 強，但 biology 保留偏弱", A_en:"Strong batch correction but weaker biology preservation",
    B:"兩者都最佳", B_en:"Best on both",
    C:"不能用", C_en:"Doesn't work",
    D:"只能 R 用", D_en:"R-only",
    ans:"A",
    exp:"Harmony 在 ST 上 batch correction 偏強但 biology 保留偏弱；STAligner 在兩個指標上較平衡。",
    exp_en:"Harmony aggressively corrects batches but loses biology in ST; STAligner balances both better." },
  { type:"single",
    stem:"想要一站式做完「批次校正 + 對位 + 3D」？",
    stem_en:"End-to-end 'batch correction + alignment + 3D reconstruction'?",
    A:"PASTE", A_en:"PASTE",
    B:"STAIR", B_en:"STAIR",
    C:"Harmony", C_en:"Harmony",
    D:"SpatialDE", D_en:"SpatialDE",
    ans:"B",
    exp:"STAIR (2025 Genome Biol) 是 end-to-end 工具：batch correction → 2D 對位 → 3D 重建。",
    exp_en:"STAIR (2025 Genome Biol) is an end-to-end tool: batch correction → 2D alignment → 3D reconstruction." },
  { type:"multi",
    stem:"下列哪些工具可以做 ST 多樣本整合？（多選）",
    stem_en:"Which tools handle ST multi-sample integration? (Multiple)",
    A:"Harmony", A_en:"Harmony",
    B:"STAligner", B_en:"STAligner",
    C:"PASTE", C_en:"PASTE",
    D:"Cellpose", D_en:"Cellpose",
    ans:["A","B","C"],
    exp:"前三者皆為整合工具。Cellpose 是 segmentation。",
    exp_en:"The first three are integration tools. Cellpose is for segmentation." },
  { type:"tf",
    stem:"是非題：對 HD 資料，sketching + Harmony 是當前最實用的多樣本整合方案之一。",
    stem_en:"True/False: For HD data, sketching + Harmony is one of the most practical multi-sample integration recipes.",
    ans:"T",
    exp:"JEFworks 2025 教學示範 sketching + Harmony 對 HD 多樣本是當前實務最佳路線。",
    exp_en:"The JEFworks 2025 tutorial demonstrates sketching + Harmony as the current practical best for multi-sample HD." },
  { type:"single",
    stem:"關於 STAligner 的核心建模思路？",
    stem_en:"Core modeling idea of STAligner?",
    A:"GNN + triplet loss，跨 platform 與條件穩定", A_en:"GNN + triplet loss, cross-platform robust",
    B:"PCA + K-means", B_en:"PCA + K-means",
    C:"是 segmentation 工具", C_en:"It is a segmentation tool",
    D:"取代 deconvolution", D_en:"Replaces deconvolution",
    ans:"A",
    exp:"STAligner（Nat Comp Sci 2023）用 GNN + triplet loss 校正 batch + 對齊空間，跨 platform 與不同條件較穩。",
    exp_en:"STAligner (Nat Comput Sci 2023) uses GNN + triplet loss to correct batches + align space, robust across platforms and conditions." },
  { type:"tf",
    stem:"是非題：在 ST 多樣本整合中，「biology preservation」與「batch correction」之間存在 trade-off。",
    stem_en:"True/False: In ST multi-sample integration, 'biology preservation' and 'batch correction' present a trade-off.",
    ans:"T",
    exp:"2025 bioRxiv benchmark 明確指出兩者是 trade-off：Harmony 偏 batch；STAligner 平衡較佳。",
    exp_en:"The 2025 bioRxiv benchmark clearly shows the trade-off: Harmony leans batch; STAligner balances better." },
  { type:"single",
    stem:"PASTE2 相對於 PASTE 的主要改進是？",
    stem_en:"Main improvement of PASTE2 over PASTE?",
    A:"支援部分對位 (partial alignment)，更能處理不完全重疊的切片", A_en:"Supports partial alignment, handling non-overlapping slices",
    B:"完全取代 PASTE", B_en:"Fully replaces PASTE",
    C:"加入 segmentation 功能", C_en:"Adds segmentation",
    D:"只能 R", D_en:"R-only",
    ans:"A",
    exp:"PASTE2（Genome Res 2024）在 PASTE 的 OT 框架上加入 partial alignment，能處理部分區域不重疊的相鄰切片。",
    exp_en:"PASTE2 (Genome Res 2024) adds partial alignment to PASTE's OT framework, handling slices that only partially overlap." }
],

"Step 14：細胞切割 (Segmentation)": [
  { type:"single",
    stem:"在 image-based ST 上 over-segmentation 會導致？",
    stem_en:"Over-segmentation in image-based ST causes:",
    A:"一顆真細胞被切成多個小細胞，表達被稀釋", A_en:"A real cell gets split into many small cells with diluted expression",
    B:"完全沒有問題", B_en:"No problem at all",
    C:"增加細胞 marker 表達", C_en:"Increases marker expression",
    D:"等同 doublet detection", D_en:"Equivalent to doublet detection",
    ans:"A",
    exp:"over-seg 把一顆細胞切成多個小細胞，每個都只有部分轉錄本，表達被稀釋、cell type 漂移。",
    exp_en:"Over-seg splits one cell into many small cells; each gets only partial transcripts, diluting expression and shifting cell types." },
  { type:"single",
    stem:"沒有 nuclear stain 影像時，下列何者最能幫忙？",
    stem_en:"Without nuclear stain, which method works best?",
    A:"Cellpose", A_en:"Cellpose",
    B:"Mesmer", B_en:"Mesmer",
    C:"Baysor / proseg（直接用 transcript 點雲）", C_en:"Baysor / proseg (uses transcript cloud directly)",
    D:"PASTE", D_en:"PASTE",
    ans:"C",
    exp:"Baysor / proseg 直接用 transcript 點雲做機率分群，不需要 nuclear stain。Cellpose / Mesmer 都需要影像。",
    exp_en:"Baysor / proseg work on transcript clouds directly without needing nuclear stain. Cellpose / Mesmer require imaging." },
  { type:"single",
    stem:"2025 bioRxiv 對 segmentation 提出的最大警告是？",
    stem_en:"Main warning from the 2025 bioRxiv on segmentation?",
    A:"Cellpose 已不再可用", A_en:"Cellpose is deprecated",
    B:"多數論文沒做 segmentation 驗證", B_en:"Most papers skip segmentation validation",
    C:"Xenium 不需要 segmentation", C_en:"Xenium needs no segmentation",
    D:"Baysor 永遠是最佳選擇", D_en:"Baysor is always optimal",
    ans:"B",
    exp:"2025 bioRxiv 系統性研究指出多數已發表 ST 研究直接套預設 segmentation 而沒驗證，是領域盲點。",
    exp_en:"The 2025 bioRxiv systematic study found that most published ST works apply default segmentation without validation — a major blind spot." },
  { type:"multi",
    stem:"下列哪些是 image-based ST 的細胞切割工具？（多選）",
    stem_en:"Which are cell segmentation tools for image-based ST? (Multiple)",
    A:"Cellpose", A_en:"Cellpose",
    B:"Baysor", B_en:"Baysor",
    C:"proseg", C_en:"proseg",
    D:"BLAST", D_en:"BLAST",
    ans:["A","B","C"],
    exp:"前三者皆為 segmentation 工具。BLAST 為序列比對。",
    exp_en:"The first three are segmentation tools. BLAST is for sequence alignment." },
  { type:"tf",
    stem:"是非題：under-segmentation 會把兩顆相鄰細胞合在一起，形成「合成 doublet」。",
    stem_en:"True/False: under-segmentation merges adjacent cells into 'synthetic doublets'.",
    ans:"T",
    exp:"under-seg 合併相鄰細胞 → 表達混合 → 形成假的 transitional / doublet 群，干擾分群。",
    exp_en:"Under-seg merges neighbors → mixed expression → creates fake transitional / doublet populations that confuse clustering." },
  { type:"single",
    stem:"關於 segmentation 後的 QC，下列何者較重要？",
    stem_en:"Important post-segmentation QC includes?",
    A:"檢查 cell area、transcript/cell、unassigned 比例", A_en:"Check cell area, transcripts/cell, % unassigned",
    B:"完全不需要 QC", B_en:"No QC needed",
    C:"只看 PCA", C_en:"Only PCA",
    D:"做 BLAST", D_en:"Run BLAST",
    ans:"A",
    exp:"segmentation 後典型 QC：細胞面積分布、每細胞 transcript 數、unassigned 比例都應該檢查。",
    exp_en:"Typical post-seg QC: cell-area distribution, transcripts/cell, and % unassigned transcripts." },
  { type:"single",
    stem:"關於 proseg 的特色，下列何者較正確？",
    stem_en:"About proseg, which is closer?",
    A:"最新 (2024) probabilistic、scalable，特別適合大型 Xenium 資料", A_en:"Newest (2024) probabilistic, scalable — great for large Xenium data",
    B:"是影像分類器", B_en:"It's an image classifier",
    C:"取代 PCA", C_en:"Replaces PCA",
    D:"不能跑在 Xenium", D_en:"Cannot run on Xenium",
    ans:"A",
    exp:"proseg 是 2024 後新出的機率切割工具，特別針對大型 Xenium 提供高速度方案。",
    exp_en:"proseg is a newer (post-2024) probabilistic segmentation tool, especially fast on large Xenium datasets." },
  { type:"single",
    stem:"關於 Cellpose 的常見輸入，下列何者較合理？",
    stem_en:"For Cellpose, what's the typical input?",
    A:"DAPI 或 membrane stain 影像", A_en:"DAPI or membrane stain image",
    B:"transcript 點雲，無影像", B_en:"transcript cloud only, no image",
    C:"PCA 矩陣", C_en:"PCA matrix",
    D:"GFF / GTF 檔", D_en:"GFF / GTF files",
    ans:"A",
    exp:"Cellpose 是基於 U-Net 的 segmentation，輸入通常是 DAPI 或 membrane stain 影像（亦支援多通道）。",
    exp_en:"Cellpose is a U-Net-based segmenter; inputs are typically DAPI or membrane stain images (multi-channel supported)." },
  { type:"tf",
    stem:"是非題：實務上，建議至少跑一個替代 segmentation 方法做 sanity check，並抽樣目視 H&E/DAPI 確認邊界合理。",
    stem_en:"True/False: In practice, run at least one alternative segmentation method for sanity check and visually verify boundaries on H&E/DAPI.",
    ans:"T",
    exp:"健康檢查清單：替代方法、目視 ROI、平均 transcript/cell、unassigned 比例都應該在報告中提供。",
    exp_en:"Sanity checklist: alternative method, visual ROI, mean transcripts/cell, and % unassigned should all appear in the report." }
],

"Step 15：Visium HD 與病理影像": [
  { type:"single",
    stem:"10x Genomics 對於 Visium HD 推薦的預設 bin 大小？",
    stem_en:"10x Genomics' recommended default bin for Visium HD?",
    A:"2 µm", A_en:"2 µm",
    B:"8 µm", B_en:"8 µm",
    C:"16 µm", C_en:"16 µm",
    D:"55 µm", D_en:"55 µm",
    ans:"B",
    exp:"原始 bin 是 2 µm 但太稀疏；10x 建議 8 µm 為下游分析預設單位，能準確定位 scRNA cell type。",
    exp_en:"Raw bins are 2 µm but too sparse; 10x recommends 8 µm as the default analysis unit, accurately localizing scRNA cell types." },
  { type:"single",
    stem:"對於記憶體吃不消的 HD 大資料，什麼策略最實用？",
    stem_en:"Most practical strategy for memory-intensive HD data?",
    A:"Sketching：抽樣 50 k bins 跑分析、再 project 回去", A_en:"Sketching: subsample 50k bins, then project back",
    B:"一次載入全部", B_en:"Load everything at once",
    C:"拒絕分析", C_en:"Refuse to analyze",
    D:"隨機刪除 90% bin", D_en:"Randomly delete 90% of bins",
    ans:"A",
    exp:"Seurat v5 SketchData 抽 50k bins → 分群 → ProjectData 回完整資料是 HD 標準做法。",
    exp_en:"Seurat v5's SketchData (50k bins → cluster → ProjectData back) is the standard HD recipe." },
  { type:"single",
    stem:"HEST-1k 的角色是？",
    stem_en:"Role of HEST-1k?",
    A:"是新的 segmentation 工具", A_en:"A new segmentation tool",
    B:"是 BANKSY 的替代品", B_en:"A BANKSY alternative",
    C:"1229 個 ST + WSI 配對的開源資料集，用來訓練 vision-omics foundation model", C_en:"Open dataset of 1 229 paired ST + WSI samples for training vision-omics foundation models",
    D:"全新的定序平台", D_en:"A new sequencing platform",
    ans:"C",
    exp:"HEST-1k（NeurIPS 2024）是 1229 個 ST + WSI 配對資料集，是訓練 vision-omics 模型的核心 benchmark。",
    exp_en:"HEST-1k (NeurIPS 2024) is a 1 229 paired ST + WSI dataset, the central benchmark for vision-omics models." },
  { type:"multi",
    stem:"下列哪些屬於 HD 工作流程的關鍵步驟？（多選）",
    stem_en:"Which are key steps in the HD workflow? (Multiple)",
    A:"Sketching 抽樣", A_en:"Sketching subsampling",
    B:"BANKSY clustering", B_en:"BANKSY clustering",
    C:"cell-binning（用 segmentation 把 2 µm bin 聚合到細胞）", C_en:"Cell-binning (aggregate 2 µm bins into cells via segmentation)",
    D:"執行 PCR primer 設計", D_en:"Run PCR primer design",
    ans:["A","B","C"],
    exp:"A、B、C 為 HD 工作流程關鍵；D 與 HD 流程無關。",
    exp_en:"A, B, C are HD workflow essentials; D is unrelated." },
  { type:"tf",
    stem:"是非題：Visium HD 2 µm bin 因為極稀疏，通常不適合單獨直接做下游分析。",
    stem_en:"True/False: Visium HD's 2 µm bins are too sparse to use alone for downstream analysis.",
    ans:"T",
    exp:"2 µm bin 訊號極稀疏，需聚合（→ 8/16 µm 或 segmentation cell）才適合下游分析。",
    exp_en:"2 µm bins are very sparse; aggregation (→ 8/16 µm bins or segmentation cells) is needed for meaningful downstream analysis." },
  { type:"single",
    stem:"關於 vision-omics foundation model 的典型應用，下列何者較不準確？",
    stem_en:"Which is LESS accurate as a typical vision-omics foundation model use?",
    A:"從 H&E 預測未測 ST 切片的 spatial expression", A_en:"Predict spatial expression for un-profiled sections from H&E",
    B:"用形態學重新解釋 ST cluster", B_en:"Re-interpret ST clusters via morphology",
    C:"找出形態相似但表達不同的隱藏亞群", C_en:"Discover hidden subpopulations with similar morphology but different expression",
    D:"取代 Cellpose 做細胞切割", D_en:"Replace Cellpose for cell segmentation",
    ans:"D",
    exp:"vision-omics foundation model 不直接做 segmentation；segmentation 仍由 Cellpose / Baysor / proseg 等專門工具負責。",
    exp_en:"Vision-omics foundation models don't perform segmentation; that remains the job of Cellpose / Baysor / proseg." },
  { type:"multi",
    stem:"下列哪些是 H&E 與 ST 整合的工具或資料集？（多選）",
    stem_en:"Which are tools or datasets for H&E + ST integration? (Multiple)",
    A:"HEST-1k", A_en:"HEST-1k",
    B:"Thor", B_en:"Thor",
    C:"SpaGCN（用 H&E 顏色當 GNN 特徵）", C_en:"SpaGCN (uses H&E color as GNN features)",
    D:"DESeq2", D_en:"DESeq2",
    ans:["A","B","C"],
    exp:"前三者皆把 H&E 與 ST 整合。DESeq2 為 bulk RNA-seq DE 工具。",
    exp_en:"The first three integrate H&E with ST. DESeq2 is for bulk RNA-seq DE." },
  { type:"single",
    stem:"關於 Visium HD 對 SCTransform / scRNA 假設的影響，下列何者較合理？",
    stem_en:"Regarding Visium HD's impact on SCTransform / scRNA assumptions, which is more reasonable?",
    A:"HD 8 µm bin 接近單細胞，SCTransform 的 NB 假設較容易回到合理範圍", A_en:"HD 8 µm bins are near-single-cell; SCTransform's NB assumption is more likely to hold",
    B:"HD 完全不能用 SCTransform", B_en:"HD cannot use SCTransform at all",
    C:"HD 一定要用 raw counts", C_en:"HD must use raw counts only",
    D:"SCTransform 在 HD 上一定錯誤", D_en:"SCTransform is always wrong on HD",
    ans:"A",
    exp:"HD 8 µm bin 已接近單細胞解析，SCTransform 的 NB 假設較合理，可比照 scRNA 應用；2 µm bin 則仍嫌稀疏。",
    exp_en:"At HD 8 µm bins, near-single-cell resolution makes SCTransform's NB assumption more tenable, similar to scRNA. 2 µm bins remain too sparse." },
  { type:"tf",
    stem:"是非題：將 H&E 與 ST 整合的 vision-omics foundation model 可省下「未測 ST 切片」的成本，從 H&E 預測表達。",
    stem_en:"True/False: Vision-omics foundation models that integrate H&E with ST can save costs by predicting expression from H&E for un-profiled sections.",
    ans:"T",
    exp:"vision-omics 模型可從 H&E patch 預測 spatial expression，特別在大隊列研究能顯著節省 ST 定序成本。",
    exp_en:"Vision-omics models can predict spatial expression from H&E patches, saving substantial ST sequencing costs in large cohorts." }
]

}

}
}
};
